### ISSUE TITLE
Folivora README update

### ISSUE THREAD

**Issue by vblaha** [disy/folivora#1]
Would you like for the readme file to contain a more comprehensive description and more information on the project? I would like to contribute to this .

**Comment by sualko** [comment]
Welcome to the team @vblaha. I updated the readme and added some screenshots so you can see how Folivora looks. We are really happy that you like to work on Folivora and if you have any questions, please don't hesitate to write me an message.

Do you have already an idea what do you want to implement?

**Comment by vblaha** [comment]
Hi!
I did a brief look over the code and did not see unit testing-is this something I can help with in the coming weeks? The readme looks wonderful-i can understand much more about the project now after reading it. Let me know if testing has already been assigned or is done and I missed it. Thank you,
V

**Comment by sualko** [comment]
Unit tests would be awesome. If you need help or anything else, please write me an email to kh@uni.kn
